In [9]:
import pandas as pd
import mysql.connector

In [10]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="samruddhi",
    database="parking"
)

print("Database connected successfully!")

Database connected successfully!

In [11]:
parking=pd.read_sql("select * from parking",conn)
parking.head()

C:\Users\ACER\AppData\Local\Temp\ipykernel_12280\1198760826.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  parking=pd.read_sql("select * from parking",conn)

,Transaction_ID,Vehicle_ID,Entry_Date,Entry_Time,Exit_Time,Parking_Duration_Minutes,Parking_Slot,Parking_Fee,Payment_Method,Day_Type,Time_Period
0,T019548,V05050,2026-01-01,06:01:00,10:31:00,270,C-240,200,Cash,Weekday,Morning
1,T002387,V03763,2026-01-01,06:07:00,10:47:00,280,A-074,200,UPI,Weekday,Morning
2,T011733,V02969,2026-01-01,06:21:00,11:41:00,320,A-005,300,Card,Weekday,Morning
3,T001095,V05400,2026-01-01,06:30:00,07:50:00,80,B-198,80,UPI,Weekday,Morning
4,T014666,V01936,2026-01-01,07:03:00,10:03:00,180,B-184,120,Card,Weekday,Morning

In [6]:
vehicle=pd.read_sql("select * from vehicle",conn)
vehicle.head()

C:\Users\ACER\AppData\Local\Temp\ipykernel_8228\575389518.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vehicle=pd.read_sql("select * from vehicle",conn)

  Vehicle_ID Vehicle_Type Customer_Type  Vehicle_Model Registration_City
0     V00001         Bike       Regular      Yamaha FZ            Satara
1     V00002          SUV           New   Tata Harrier            Nashik
2     V00003          Car       Regular  Maruti Baleno            Nashik
3     V00004          Car       Regular   Maruti Swift            Satara
4     V00005         Bike           New    TVS Jupiter            Nashik

In [8]:
parking.shape

(20000, 11)

In [9]:
vehicle.shape

(6000, 5)

In [ ]:
# PARKING ANALYSIS

In [10]:
#1. What is the total number of parking transactions?
parking.count()

Transaction_ID              20000
Vehicle_ID                  20000
Entry_Date                  20000
Entry_Time                  20000
Exit_Time                   20000
Parking_Duration_Minutes    20000
Parking_Slot                20000
Parking_Fee                 20000
Payment_Method              20000
Day_Type                    20000
Time_Period                 20000
dtype: int64

In [18]:
#2. What is the total parking revenue generated?
total_revenue = parking["Parking_Fee"].sum()
print("Total Revenue:", total_revenue)

Total Revenue: 2405180

In [23]:
#3. What is the average parking fee?
parking_fee = parking["Parking_Fee"].mean()
print("Average_parking_fee :",parking_fee)

Average_parking_fee : 120.259

In [24]:
#4. What is the average parking duration?
parking_duration = parking["Parking_Duration_Minutes"].mean()
print("Average_parking_duration :",parking_duration)

Average_parking_duration : 185.3105

In [ ]:
# PAYMENT ANALYSIS

In [29]:
#5. Which payment method is used the most?
parking["Payment_Method"].value_counts

<bound method IndexOpsMixin.value_counts of 0        Cash
1         UPI
2        Card
3         UPI
4        Card
         ...
19995    Card
19996    Card
19997    Card
19998     UPI
19999    Card
Name: Payment_Method, Length: 20000, dtype: str>

In [30]:
#6. Which payment method generates the highest revenue?
parking .groupby("Payment_Method")["Parking_Fee"].sum()

Payment_Method
Card     592080
Cash     560560
UPI     1252540
Name: Parking_Fee, dtype: int64

In [ ]:
# TIME ANALYSIS

In [32]:
#7. Which time period has the highest number of transactions?
parking["Time_Period"].value_counts()

Time_Period
Afternoon    8355
Morning      5400
Evening      5243
Night        1002
Name: count, dtype: int64

In [33]:
#8. Which time period generates the highest revenue?
parking.groupby("Time_Period")["Parking_Fee"].sum()

Time_Period
Afternoon    1006780
Evening       634470
Morning       646000
Night         117930
Name: Parking_Fee, dtype: int64

In [35]:
#9. Are there more transactions on weekdays or weekends?
parking["Day_Type"].value_counts()

Day_Type
Weekday    14365
Weekend     5635
Name: count, dtype: int64

In [36]:
#10. Which day type generates higher revenue?
parking.groupby("Day_Type")["Parking_Fee"].sum()

Day_Type
Weekday    1725590
Weekend     679590
Name: Parking_Fee, dtype: int64

In [ ]:
# Vehicle Analysis

In [42]:
data = pd.merge(parking, vehicle, on="Vehicle_ID", how="inner")

In [43]:
#11. Which vehicle type has the highest number of transactions?
vehicle_transaction = data["Vehicle_Type"].value_counts()
print(vehicle_transaction)

Vehicle_Type
Car     8988
Bike    8386
SUV     2626
Name: count, dtype: int64

In [45]:
#12. Which vehicle type generates the highest revenue?
data.groupby("Vehicle_Type")["Parking_Fee"].sum().sort_values(ascending=False)

Vehicle_Type
Car     1354120
SUV      538800
Bike     512260
Name: Parking_Fee, dtype: int64

In [46]:
#13. Which vehicle type has the highest average parking duration?
data.groupby("Vehicle_Type")["Parking_Duration_Minutes"].mean()

Vehicle_Type
Bike    157.921536
Car     200.456164
SUV     220.936786
Name: Parking_Duration_Minutes, dtype: float64

In [ ]:
# CUSTOMER ANALYSIS

In [48]:
#14. How many vehicles are New and Regular customers?
data["Customer_Type"].value_counts()

Customer_Type
Regular    12881
New         7119
Name: count, dtype: int64

In [49]:
#15. Which customer type has the highest number of transactions?
data["Customer_Type"].value_counts()

Customer_Type
Regular    12881
New         7119
Name: count, dtype: int64

In [50]:
#16. Which customer type generates the highest revenue?
data.groupby("Customer_Type")["Parking_Fee"].sum()

Customer_Type
New         862460
Regular    1542720
Name: Parking_Fee, dtype: int64

In [ ]:
# Registration City Analysis

In [52]:
#17. Which registration city has the highest number of vehicles
vehicle["Registration_City"].value_counts()

Registration_City
Pune        2399
Mumbai      1069
Nashik       762
Other        651
Satara       631
Kolhapur     488
Name: count, dtype: int64

In [54]:
#18. Which registration city has the highest number of parking transactions
data["Registration_City"].value_counts().sort_values(ascending=False)

Registration_City
Pune        8089
Mumbai      3549
Nashik      2615
Satara      2092
Other       2049
Kolhapur    1606
Name: count, dtype: int64

In [57]:
#19. Which registration city generates the highest revenue?
data.groupby("Registration_City")["Parking_Fee"].sum().sort_values(ascending=False)

Registration_City
Pune        959230
Mumbai      427230
Nashik      313660
Satara      259270
Other       250170
Kolhapur    195620
Name: Parking_Fee, dtype: int64

In [ ]:
# Parking Slot & Monthly Analysis

In [59]:
#20. Which parking slot is used the most?
parking["Parking_Slot"].value_counts()

Parking_Slot
B-092    42
B-142    40
B-034    38
B-115    37
A-147    37
         ..
D-203     7
D-135     7
C-212     6
D-234     5
C-115     4
Name: count, Length: 1000, dtype: int64

In [5]:
#21. How much revenue is generated in each month?
parking["Entry_Date"] = pd.to_datetime(parking["Entry_Date"])

monthly_revenue = parking.groupby(
    parking["Entry_Date"].dt.month
)["Parking_Fee"].sum()

print(monthly_revenue)

Entry_Date
1     201450
2     178880
3     198230
4     198950
5     193900
6     194590
7     194030
8     215230
9     206640
10    215530
11    200770
12    206980
Name: Parking_Fee, dtype: int64

In [13]:
#22. Which month generated the highest revenue?


parking["Entry_Date"] = pd.to_datetime(parking["Entry_Date"])
parking["Month"] = parking["Entry_Date"].dt.month_name()

monthly_revenue = parking.groupby("Month")["Parking_Fee"].sum()

print(monthly_revenue)

Month
April        198950
August       215230
December     206980
February     178880
January      201450
July         194030
June         194590
March        198230
May          193900
November     200770
October      215530
September    206640
Name: Parking_Fee, dtype: int64